COMMANDS_PATH = "./commands/jarvis/app/commands"
COMMANDS_FILE_NAME = "command.yaml"
SOUNDS_PATH = "./sounds"
AUTOHOTKEY_PATH = r"C:\Program Files\AutoHotkey\v2\AutoHotkey.exe"
WAKE_WORLD_SOUND_NAME = "wake_world"
END_OF_USER_PHRASE_SOUND_NAME = "end_of_user_phrase_sound"
GIGACHAT_TOKEN_EXPIRE_FILE_PATH = "./temp_files/expire_token.txt"